language: c
os: linux

matrix:
  include:
  - compiler: clang
    script:
      - make
  - compiler: gcc
    script:
      - make
  - script:
      - clang-format -i filet.c && git diff --exit-code
    addons:
      apt:
        packages:
          - clang-format
