language: c
os: linux

matrix:
  include:
  - compiler: clang
    script:
      - make
  - compiler: gcc
    script:
      - make
  - compiler: clang
    script:
      - sed -i '27d'
      - clang-format -i filet.c && git diff --exit-code
