.TH FILET 1 "May 15, 2020"
.
.SH NAME
filet \- fucking fucking fast file fucker
.
.SH SYNOPSIS
\fBfilet\fP [\fIdirectory\fP]
.
.SH DESCRIPTION
\fBfilet\fP is a blazingly fast, lightweight file manager, with a focus on a
clear and easy to understand code base.
\fBfilet\fP writes the directory you quit in into \fI/tmp/filet_dir\fP.
\fBfilet\fP writes the file you quit on into \fI/tmp/filet_sel\fP.
.
.PP
\fIFILET_DEPTH\fR is used to indicate how many of \fBfilet\fP's shells you're
in right now.
.
.SH USAGE
.TP
\fBj k\fP
Move up/down
.
.TP
\fBh l\fP
Leave/enter directory
.
.TP
\fBl RET\fP
Open file using \fIFILET_OPENER\fR
.
.TP
\fB~ /\fP
Move to home/root
.
.TP
\fB\&.\fP
Toggle visibility of dotfiles
.
.TP
\fBr\fP
Reload dir
.
.TP
\fBg G\fP
Go to top/bottom
.
.TP
\fBe\fP
Edit using \fIEDITOR\fR
.
.TP
\fBs\fP
Spawn a \fISHELL\fR
.
.TP
\fBm\fP
Mark an item as selected
.
.TP
\fBx\fP
Delete current selection
.
.TP
\fBq\fP
Quit
.
.SH AUTHOR
Niclas Meyer <niclas at countingsort.com>.
For more information see https://github.com/buffet/filet.
